### ISSUE TITLE
Explain how to run locally

### ISSUE THREAD

**Issue by sepastian** [IllumiDesk/illumidesk#624]
**Is your feature request related to a problem? Please describe.**

The README.md [explains](https://github.com/IllumiDesk/illumidesk#building-the-jupyterhubs) how to build for local testing with `docker-compose` and `docker`. It does not explain how to actually perform local testing after building. There are no docker-compose files.

**Describe the solution you'd like**

A `docker-compose.yml` file.

**Describe alternatives you've considered**

A `docker run` command(s).

**Additional context**

n/a

**Comment by jgwerner** [comment]
Hi, @sepastian thanks for opening the issue. This is a good request and we are actually working on attempting to implement a viable solution for local setups again. We did have a solution working with `docker-compose` + `ansible` in the past but have since moved to Kubernetes.

You may look at this legacy setup by [visiting this commit of the source](https://github.com/IllumiDesk/illumidesk/tree/90cc2b13e106cb0876bf589ea2e2b7f926fe677f). The Readme should include all the instructions for you to get up and running. However, keep in mind that this old version required an `nbgrader` fork that we no longer maintain. In order for this legacy code to work, simply use the standard `jupyterhub/ltiauthenticator` as a replacement for the included LTI 1.1 / LTI 1.3 authenticators.

Moving forward, we are "all-in" with Kubernetes and plan to provide local setup options with [Kind](https://kind.sigs.k8s.io/docs/user/local-registry/). For the time being, we will remove the docker-compose reference to remove confusion.
