### ISSUE TITLE
course_id is not optional with lti11_enabled = false and lit13_enabled=false

### ISSUE THREAD

**Issue by jmburges** [IllumiDesk/illumidesk#83]
**Describe the bug**
The `hosts.example` file says that the `course_id` variable is optional. If you don't fill it out and keep `lti11_enabled` and `lti13_enabled` to `false`, then the `docker-compose.yml` template creates an invalid YAML file. 

Either, `course_id` needs to be in the required section of the `hosts.example` or there needs to be an additional check for an empty `course_id` on this line: https://github.com/IllumiDesk/illumidesk/blob/master/ansible/roles/jupyterhub/templates/docker-compose.yml.j2#L43 . I'm not sure which is the correct solution given all the other downstream effects of those changes.

**To Reproduce**
1. Clone master.
2. copy `hosts.example` to `hosts`.
3. change just the `ansible_host`, `ansible_port`, `ansible_user`, `ansible_ssh_private_key_file`, and `ansible_password` to whatever it should be
4. `make deploy`

**Expected behavior**
Successful install and launch of all the docker containers

**Actual Behavior**
```
TASK [launch : launch with docker-compose] ***************************************************************************
fatal: [illumidesk]: FAILED! => {"changed": true, "cmd": ["docker-compose", "up", "-d"], "delta": "0:00:00.562821", "end": "2020-05-25 08:28:47.208785", "msg": "non-zero return code", "rc": 1, "start": "2020-05-25 08:28:46.645964", "stderr": "yaml.parser.ParserError: while parsing a block mapping\n  in \"./docker-compose.yml\", line 4, column 3\nexpected <block end>, but found ':'\n  in \"./docker-compose.yml\", line 43, column 3", "stderr_lines": ["yaml.parser.ParserError: while parsing a block mapping", "  in \"./docker-compose.yml\", line 4, column 3", "expected <block end>, but found ':'", "  in \"./docker-compose.yml\", line 43, column 3"], "stdout": "", "stdout_lines": []}
```

**Additional context**

**Comment by jgwerner** [comment]
@jmburges great point, and thank you for providing us with this detailed feedback.

The documentation should clarify that the `course_id` variable should have a value if in fact this variable is included in the `hosts` yaml file. The `hosts.example` file does include `course_id` in the required section, however, it doesn't have a value assigned to it. The empty value overrides the default four course_id (`intro101`) and breaks the `docker-compose.yaml` based setup.

We will push a fix to instruct users to change the default value instead of providing them with a blank placeholder.
